### ISSUE TITLE
Feature request: OData CRUD URLs & samples

### ISSUE THREAD

**Issue by CarmelSoftware** [CarmelSoftware/OrchidsSPA#1]
Need for uploading OData CRUD URLs that are used by this AngularJS SPA App.
Preferable if samples of OData queries are fully demonstrated , together with the
data that is fetched by those REST requests.
Specifically, need for HTTP GET, HTTP PATCH, HTTP POST & HTTP DELETE.

**Comment by CarmelSchvartzman** [comment]
Added Delete template file
